version = 0.1

[default.deploy.parameters]
stack_name = "spotify-listening"
resolve_s3 = true
s3_prefix = "spotify-listening"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "BucketName=\"spotify-listening-intelligence-522814719052\""
image_repositories = []
