version = 0.1

[default.deploy.parameters]
stack_name = "spotify-extract-stack"
resolve_s3 = true
s3_prefix = "spotify-extract-stack"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
